### ISSUE TITLE
move post title to top of page

### ISSUE THREAD

**Issue by PathfinderCTO** [404pandas/momentum-blog#2]
![Screenshot 2023-10-25 at 6 59 06 AM](https://github.com/404pandas/momentum-blog/assets/141790383/3d71b1b3-0ff6-45f7-a935-74b46133522f)

Title of blog posts is showing in the left gutter but should be at the top of the page

**Comment by 404pandas** [comment]
[
![Screenshot 2024-07-03 at 11 30 52 PM](https://github.com/404pandas/momentum-blog/assets/113853550/95b215e3-93fd-463a-b6de-429a203bcdaf)
](url)

I found the issue- they had their flexbox going in a row. I switched it to column, and redid the grid so that the date stayed in the top left how it was originally.  The testing suite doesn't render all the items that are linked to your account, so items like '/ 1 min read' will be absent until it's live. What do you think, @PathfinderCTO ?
